name: CI frontend

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: ビルドとチェック
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: 依存パッケージをインストール
        run: npm ci

      - name: ESLintを実行
        run: npm run lint

      - name: Next.jsをビルド
        run: npm run build